project:
  kafka:
    broker1:
      host: 192.168.1.5:9092
      group-id: myGroup
      auto-commit-interval: 50
      max-poll-interval: 500
      max-poll-records: 5
    broker2:
      host: 192.168.1.3:9093
      group-id: myGroup2
      ssl-stores:
        - user3
  rest:
    eurookna:
      host: http://www.google.com
      trust-strategy: NOT_USED
    request2:
      host: http://google.com
      port: 8080
      mapping: index
      trust-strategy:  NOT_USED
  sslStores:
    user1:
      keystore-location: userStores//key1.jks
      keystore-password: pass1234
    user2:
      truststore-type: JKS
      keystore-type: JKS
      truststore-location: resources\userStores\client.truststore.jks
      keystore-location: resources\userStores\server.truststore.jks
      truststore-password: key1234
      keystore-password: key1234
    user3:
      truststore-type: JKS
      keystore-type: JKS
      truststore-location: userStores//trust3.jks
      keystore-location: userStores//key3.jks
      truststore-password: pass1234
      keystore-password: pass1234
    user4:
      truststore-type: JKS
      keystore-type: JKS
      truststore-location: userStores//trust4.jks
      keystore-location: userStores//key4.jks
      truststore-password: pass1234
      keystore-password: pass1234