project:
  kafka:
    broker1:
      host: 127.0.0.1:9090
      groupId: myGroup
    broker2:
      host: 127.0.0.1:9092
      groupId: myGroup2
      sslStores:
        - user3
        - user4
  rest:
    request1:
      host: http://google.com/
      port: 8080
      mapping: index
      sslStore: user1
      trustStrategy: TRUST_SELF_SIGNED
    request2:
      host: http://google.com/
      port: 8080
      mapping: index
      trustStrategy:  NO
  sslStores:
    user1:
      keystoreLocation: userStores//key1.jks
      keystorePassword: pass1234
    user2:
      truststoreType: JKS
      keystoreType: JKS
      truststoreLocation: userStores//trust2.jks
      keystoreLocation: userStores//key2.jks
      truststorePassword: pass1234
      keystorePassword: pass1234
    user3:
      truststoreType: JKS
      keystoreType: JKS
      truststoreLocation: userStores//trust3.jks
      keystoreLocation: userStores//key3.jks
      truststorePassword: pass1234
      keystorePassword: pass1234
    user4:
      truststoreType: JKS
      keystoreType: JKS
      truststoreLocation: userStores//trust4.jks
      keystoreLocation: userStores//key4.jks
      truststorePassword: pass1234
      keystorePassword: pass1234