project:
  kafka:
    broker1:
      host: 192.168.1.3:9092
      groupId: myGroup
    broker2:
      host: 192.168.1.3:9093
      groupId: myGroup2
      sslStores:
        - user3
  rest:
    eurookna:
      host: https://www.eurookna.ru/
      trustStrategy: NOT_USED
    request2:
      host: http://google.com/
      port: 8080
      mapping: index
      trustStrategy:  NOT_USED
  sslStores:
    user1:
      keystoreLocation: userStores//key1.jks
      keystorePassword: pass1234
    user2:
      truststoreType: JKS
      keystoreType: JKS
      truststoreLocation: resources\userStores\client.truststore.jks
      keystoreLocation: resources\userStores\server.truststore.jks
      truststorePassword: key1234
      keystorePassword: key1234
    user3:
      truststoreType: JKS
      keystoreType: JKS
      truststoreLocation: userStores//trust3.jks
      keystoreLocation: userStores//key3.jks
      truststorePassword: pass1234
      keystorePassword: pass1234
    user4:
      truststoreType: JKS
      keystoreType: JKS
      truststoreLocation: userStores//trust4.jks
      keystoreLocation: userStores//key4.jks
      truststorePassword: pass1234
      keystorePassword: pass1234